// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../index.js";

/**
 * @example
 *     {
 *         size: 1,
 *         start: "start",
 *         consumerId: "consumer_id",
 *         status: "active"
 *     }
 */
export interface PaymentMethodsListRequest {
    size?: number;
    start?: string;
    /** Optional consumer UUID to list payment methods for one customer. */
    consumerId?: string;
    /** Resource status filter. Defaults to active. */
    status?: BasisTheory.agentic.PaymentMethodsListRequestStatus;
}
