// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../../index.js";
import { SharedPaymentAmount } from "../../../../../../../../types/SharedPaymentAmount.js";
import { SharedPaymentMerchant } from "../../../../../../../../types/SharedPaymentMerchant.js";
import { CreatePaymentCredentialRequestCredential } from "../../types/CreatePaymentCredentialRequestCredential.js";
import { CreatePaymentCredentialRequestProvider } from "../../types/CreatePaymentCredentialRequestProvider.js";
import { CreatePaymentCredentialRequestRail } from "../../types/CreatePaymentCredentialRequestRail.js";

export const CreatePaymentCredentialRequest: core.serialization.Schema<
    serializers.agentic.allowances.CreatePaymentCredentialRequest.Raw,
    Omit<BasisTheory.agentic.allowances.CreatePaymentCredentialRequest, "btIdempotencyKey">
> = core.serialization.object({
    rail: CreatePaymentCredentialRequestRail,
    provider: CreatePaymentCredentialRequestProvider,
    amount: SharedPaymentAmount.optional(),
    merchant: SharedPaymentMerchant.optional(),
    credential: CreatePaymentCredentialRequestCredential,
});

export declare namespace CreatePaymentCredentialRequest {
    export interface Raw {
        rail: CreatePaymentCredentialRequestRail.Raw;
        provider: CreatePaymentCredentialRequestProvider.Raw;
        amount?: SharedPaymentAmount.Raw | null;
        merchant?: SharedPaymentMerchant.Raw | null;
        credential: CreatePaymentCredentialRequestCredential.Raw;
    }
}
