/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as BasisTheory from "../index";

export class ForbiddenError extends errors.BasisTheoryError {
    constructor(body: BasisTheory.ProblemDetails) {
        super({
            message: "ForbiddenError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, ForbiddenError.prototype);
    }
}
