// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";

export const CreatePaymentCredentialRequestCredentialCard: core.serialization.ObjectSchema<
    serializers.agentic.allowances.CreatePaymentCredentialRequestCredentialCard.Raw,
    BasisTheory.agentic.allowances.CreatePaymentCredentialRequestCredentialCard
> = core.serialization.object({});

export declare namespace CreatePaymentCredentialRequestCredentialCard {
    export type Raw = {};
}
