/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as BasisTheory from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateWebhookRequest: core.serialization.Schema<
    serializers.UpdateWebhookRequest.Raw,
    BasisTheory.UpdateWebhookRequest
> = core.serialization.object({
    name: core.serialization.string(),
    url: core.serialization.string(),
    notifyEmail: core.serialization.property("notify_email", core.serialization.string().optional()),
    events: core.serialization.list(core.serialization.string()),
});

export declare namespace UpdateWebhookRequest {
    interface Raw {
        name: string;
        url: string;
        notify_email?: string | null;
        events: string[];
    }
}
