// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateWebhookRequest: core.serialization.Schema<
    serializers.UpdateWebhookRequest.Raw,
    BasisTheory.UpdateWebhookRequest
> = core.serialization.object({
    name: core.serialization.string(),
    url: core.serialization.string(),
    notifyEmail: core.serialization.property("notify_email", core.serialization.string().optional()),
    events: core.serialization.list(core.serialization.string()),
});

export declare namespace UpdateWebhookRequest {
    export interface Raw {
        name: string;
        url: string;
        notify_email?: string | null;
        events: string[];
    }
}
