// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../../index.js";

export const SubmitOtpRequest: core.serialization.Schema<
    serializers.agentic.enrollments.SubmitOtpRequest.Raw,
    BasisTheory.agentic.enrollments.SubmitOtpRequest
> = core.serialization.object({
    otpCode: core.serialization.property("otp_code", core.serialization.string()),
});

export declare namespace SubmitOtpRequest {
    export interface Raw {
        otp_code: string;
    }
}
