// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { MppStripeChallenge } from "../../../../../../../types/MppStripeChallenge.js";

export const CreateInstructionRequestMpp: core.serialization.ObjectSchema<
    serializers.agentic.agents.CreateInstructionRequestMpp.Raw,
    BasisTheory.agentic.agents.CreateInstructionRequestMpp
> = core.serialization.object({
    challenge: MppStripeChallenge,
});

export declare namespace CreateInstructionRequestMpp {
    export interface Raw {
        challenge: MppStripeChallenge.Raw;
    }
}
