// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AllowancesUpdateRequest {
    amount?: BasisTheory.SharedPaymentAmount;
    /** Customer-facing prompt describing what the allowance permits. */
    description?: string;
    /** ISO 8601 timestamp when the allowance expires. Must be in the future. */
    expiresAt?: Date;
}
