// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         size: 1,
 *         start: "start"
 *     }
 */
export interface AllowancesErrorsRequest {
    size?: number;
    start?: string;
}
