/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ApplePayCreateRequest {
    expires_at?: string;
    apple_payment_data?: BasisTheory.ApplePayMethodToken;
}
