/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../../../../index";

/**
 * @example
 *     {}
 */
export interface CreateThreeDsSessionRequest {
    pan?: string;
    tokenId?: string;
    tokenIntentId?: string;
    type?: string;
    device?: string;
    deviceInfo?: BasisTheory.ThreeDsDeviceInfo;
}
