// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const ApplePayMerchantRegisterRequest: core.serialization.Schema<
    serializers.applePay.ApplePayMerchantRegisterRequest.Raw,
    BasisTheory.applePay.ApplePayMerchantRegisterRequest
> = core.serialization.object({
    merchantIdentifier: core.serialization.property("merchant_identifier", core.serialization.string().optional()),
});

export declare namespace ApplePayMerchantRegisterRequest {
    export interface Raw {
        merchant_identifier?: string | null;
    }
}
