// This file was auto-generated by Fern from our API Definition.

export const CreatePaymentCredentialRequestProvider = {
    Vic: "vic",
    Agentpay: "agentpay",
    Stripe: "stripe",
    Link: "link",
} as const;
export type CreatePaymentCredentialRequestProvider =
    (typeof CreatePaymentCredentialRequestProvider)[keyof typeof CreatePaymentCredentialRequestProvider];
