// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface AllowanceRail {
    rail?: "virtual-card";
    provider?: "link";
    /** Provider-native reference identifiers for this rail. Informational; use for support and correlation, not as a stable contract. */
    providerIds?: Record<string, string>;
    /** Credential representations accepted by this rail/provider when minting. card, network-token, and identifier are direct API credentials; mpp is an HTTP Machine Payments Protocol credential. */
    credentialFormats: BasisTheory.AllowanceRailCredentialFormatsItem[];
    status?: "error";
    error?: BasisTheory.SharedPaymentRailError;
}
