// This file was auto-generated by Fern from our API Definition.

export const AllowanceRailCredentialFormatsItem = {
    Card: "card",
    NetworkToken: "network-token",
    Identifier: "identifier",
    Mpp: "mpp",
} as const;
export type AllowanceRailCredentialFormatsItem =
    (typeof AllowanceRailCredentialFormatsItem)[keyof typeof AllowanceRailCredentialFormatsItem];
