// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface Allowance {
    id?: string;
    paymentMethodId?: string;
    /** Optional agent attribution. This is informational and is not an authorization grant. */
    agentId?: string;
    status?: BasisTheory.AllowanceStatus;
    amount?: BasisTheory.SharedPaymentAmount;
    description?: string;
    /** Merchant the allowance is scoped to. Absent on an open allowance, which supplies a merchant per credential request instead. */
    merchant?: BasisTheory.SharedPaymentMerchant;
    amountSpent?: BasisTheory.SharedPaymentAmount;
    amountReserved?: BasisTheory.SharedPaymentAmount;
    amountAvailable?: BasisTheory.SharedPaymentAmount;
    credentialsCount?: number;
    metadata?: Record<string, unknown>;
    rails?: BasisTheory.AllowanceRail[];
    createdAt?: Date;
    updatedAt?: Date;
}
