// This file was auto-generated by Fern from our API Definition.

export interface ApplePayMerchantCertificates {
    id?: string;
    tenantId?: string;
    domain?: string;
    merchantCertificateExpirationDate?: Date;
    merchantCertificateFingerprint?: string;
    paymentProcessorCertificateExpirationDate?: Date;
    paymentProcessorCertificateFingerprint?: string;
    createdBy?: string;
    createdAt?: Date;
}
