// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface CardArt {
    backgroundColor?: string;
    logo?: BasisTheory.CardArtImage;
    cardImage?: BasisTheory.CardArtImage;
}
