/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Card {
    number?: string;
    expiration_month?: number;
    expiration_year?: number;
    cvc?: string;
}
