/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../index";

export interface CardholderInfo {
    name?: string;
    address?: BasisTheory.Address;
}
