// This file was auto-generated by Fern from our API Definition.

/**
 * Requested and granted are different things and are never merged. A provider may grant a subset of what was asked for, and some providers cannot report their grant at all.
 */
export interface ConnectionPermissions {
    /** Namespace the permission strings belong to. Basis Theory does not normalize provider permissions into its own enum, so this is what makes three strings and seventy-six interpretable in one field. */
    vocabulary: string;
    requested: string[];
    granted: string[];
    /** False when the provider gives us no way to read the grant back — a pasted API key, for instance. `granted` is then our best assertion rather than an observation, and `status_details.cause` is `unverified`. */
    grantedVerified: boolean;
}
