// This file was auto-generated by Fern from our API Definition.

export const ConnectionStatusDetailsAction = {
    Authorize: "authorize",
    Reauthorize: "reauthorize",
    None: "none",
} as const;
export type ConnectionStatusDetailsAction =
    (typeof ConnectionStatusDetailsAction)[keyof typeof ConnectionStatusDetailsAction];
