// This file was auto-generated by Fern from our API Definition.

/** Version of the result CSV format. Version '1' returns base columns. Version '1.1' adds new_fingerprint and new_brand columns. */
export const CreateAccountUpdaterJobRequestResultVersion = {
    One: "1",
    One1: "1.1",
} as const;
export type CreateAccountUpdaterJobRequestResultVersion =
    (typeof CreateAccountUpdaterJobRequestResultVersion)[keyof typeof CreateAccountUpdaterJobRequestResultVersion];
