// This file was auto-generated by Fern from our API Definition.

export interface Credentials {
    cardNumber?: string;
    expirationMonth?: number;
    expirationYear?: number;
    cvc?: string;
}
