// This file was auto-generated by Fern from our API Definition.

export const DeliveryMethod = {
    NoDelivery: "no-delivery",
    AddressBilling: "address-billing",
    AddressOnFile: "address-on-file",
    AddressOther: "address-other",
    Pickup: "pickup",
    Electronic: "electronic",
} as const;
export type DeliveryMethod = (typeof DeliveryMethod)[keyof typeof DeliveryMethod];
