// This file was auto-generated by Fern from our API Definition.

/** Enrollment type — `agentic` (default) for agent-driven payments, `autofill` for direct credential autofill. */
export const EnrollmentType = {
    Agentic: "agentic",
    Autofill: "autofill",
} as const;
export type EnrollmentType = (typeof EnrollmentType)[keyof typeof EnrollmentType];
