// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface GooglePayToken {
    id?: string;
    tenantId?: string;
    status?: string;
    expiresAt?: Date;
    createdBy?: string;
    createdAt?: Date;
    modifiedBy?: string;
    modifiedAt?: Date;
    card?: BasisTheory.CardDetails;
    data?: unknown;
    authentication?: BasisTheory.TokenAuthentication;
    details?: BasisTheory.TokenServiceProviderDetails;
    fingerprint?: string;
}
