// This file was auto-generated by Fern from our API Definition.

export interface Log {
    id?: string;
    tenantId?: string;
    actorId?: string;
    actorType?: string;
    entityType?: string;
    entityId?: string;
    operation?: string;
    message?: string;
    createdAt?: Date;
}
