// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface MerchantInfo {
    fullLegalName?: string;
    doingBusinessAs?: string;
    parentCompanyName?: string;
    websiteUrl?: string;
    categoryCodeMcc?: string;
    descriptor?: string;
    businessDescription?: string;
    registration?: BasisTheory.MerchantRegistration;
    contact?: BasisTheory.MerchantContact;
    address?: BasisTheory.MerchantAddress;
}
