/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Pagination {
    total_items?: number;
    page_number?: number;
    page_size?: number;
    total_pages?: number;
    after?: string;
    next?: string;
}
