// This file was auto-generated by Fern from our API Definition.

/** The set a payment method can actually carry today. `stablecoin_wallet` and `bnpl_account` are listed on ConnectionInstrument and can be enumerated, but no rail funds them yet, so sourcing one fails before a payment method exists. `other` is an instrument the provider offers that Basis Theory could not classify. */
export const PaymentMethodInstrumentType = {
    Card: "card",
    BankAccount: "bank_account",
    Other: "other",
} as const;
export type PaymentMethodInstrumentType =
    (typeof PaymentMethodInstrumentType)[keyof typeof PaymentMethodInstrumentType];
