// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface RequestedProxy {
    proxy?: BasisTheory.PendingProxy;
    errorCode?: string;
    errorMessage?: string;
    errorDetails?: Record<string, unknown>;
}
