// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface Runtime {
    image?: string;
    dependencies?: Record<string, string>;
    resolutions?: Record<string, string>;
    warmConcurrency?: number;
    timeout?: number;
    resources?: string;
    permissions?: string[];
    logs?: BasisTheory.RuntimeLogOptions;
}
