// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface SharedPaymentProviderError {
    id: string;
    /** Stable Agentic Commerce error code. */
    code: string;
    /** Stable Basis Theory-controlled summary suitable for display. */
    title: string;
    /** Sanitized Basis Theory-controlled remediation guidance suitable for display. */
    detail: string;
    /** Who failed. Errors recorded on a payment method or allowance name the rail provider (`vic`, `agentpay`, `stripe`, `link`); errors recorded on a source connection name the connection provider (`stripe_link`). Both appear because one wallet provider can stand behind a rail and a connection with different names. */
    provider: BasisTheory.SharedPaymentProviderErrorProvider;
    operation?: string;
    rail?: string;
    connectionId?: string;
    /** Provider-native machine-readable code when available. */
    providerCode?: string;
    /** Safe provider correlation identifier for support. */
    providerCorrelationId?: string;
    paymentMethodId?: string;
    allowanceId?: string;
    /** Generated credential attempt ID; the credential resource may not exist when minting failed. */
    paymentCredentialId?: string;
    occurredAt: Date;
}
