// This file was auto-generated by Fern from our API Definition.

export interface SharedPaymentCardDisplay {
    artUrl?: string;
    backgroundColor?: string;
    foregroundColor?: string;
    description?: string;
    issuerName?: string;
}
