// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../index.js";

export interface SharedPaymentCard {
    /** Card network reported by the vault. `agentic-token` rails require `visa` or `mastercard`; the `spt` rail accepts any network Stripe supports, so treat this as an open string rather than a closed set. */
    brand?: string;
    bin?: string;
    last4?: string;
    expirationMonth?: number;
    expirationYear?: number;
    funding?: string;
    issuer?: BasisTheory.SharedPaymentCardIssuer;
    issuerCountry?: BasisTheory.SharedPaymentCardIssuerCountry;
    segment?: string;
    type?: string;
    display?: BasisTheory.SharedPaymentCardDisplay;
}
