// This file was auto-generated by Fern from our API Definition.

export interface ShippingAddress {
    line1: string;
    city: string;
    state: string;
    postalCode: string;
    countryCode: string;
}
