// This file was auto-generated by Fern from our API Definition.

export const TenantInvitationStatus = {
    Pending: "PENDING",
    Expired: "EXPIRED",
} as const;
export type TenantInvitationStatus = (typeof TenantInvitationStatus)[keyof typeof TenantInvitationStatus];
