/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TenantInvitationStatus = "PENDING" | "EXPIRED";

export const TenantInvitationStatus = {
    Pending: "PENDING",
    Expired: "EXPIRED",
} as const;
