/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../index.js";

export interface ThreeDsAuthentication {
    pan_token_id?: string;
    token_id?: string;
    token_intent_id?: string;
    session_id?: string;
    threeds_version?: string;
    acs_transaction_id?: string;
    ds_transaction_id?: string;
    sdk_transaction_id?: string;
    acs_reference_number?: string;
    ds_reference_number?: string;
    liability_shifted?: boolean;
    authentication_value?: string;
    authentication_status?: string;
    authentication_status_code?: string;
    directory_status_code?: string;
    authentication_status_reason?: string;
    authentication_status_reason_code?: string;
    eci?: string;
    acs_challenge_mandated?: string;
    acs_decoupled_authentication?: string;
    authentication_challenge_type?: string;
    acs_rendering_type?: BasisTheory.ThreeDsAcsRenderingType;
    acs_signed_content?: string;
    acs_challenge_url?: string;
    challenge_preference?: string;
    challenge_preference_code?: string;
    challenge_attempts?: string;
    challenge_cancel_reason?: string;
    challenge_cancel_reason_code?: string;
    cardholder_info?: string;
    whitelist_status?: string;
    whitelist_status_source?: string;
    message_extensions?: BasisTheory.ThreeDsMessageExtension[];
}
