/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../index.js";

export interface ThreeDsSession {
    id?: string;
    type?: string;
    tenant_id?: string;
    pan_token_id?: string;
    token_id?: string;
    token_intent_id?: string;
    card_brand?: string;
    additional_card_brands?: string[];
    expiration_date?: string;
    created_date?: string;
    created_by?: string;
    modified_date?: string;
    modified_by?: string;
    device?: string;
    device_info?: BasisTheory.ThreeDsDeviceInfo;
    web_challenge_mode?: string;
    version?: BasisTheory.ThreeDsVersion;
    method?: BasisTheory.ThreeDsMethod;
    authentication?: BasisTheory.ThreeDsAuthentication;
}
