/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../index.js";

export interface TokenServiceProviderDetails {
    tsp?: string;
    authMethod?: string;
    messageId?: string;
    eciIndicator?: string;
    assuranceDetails?: BasisTheory.AssuranceDetails;
    transactionId?: string;
    currencyCode?: string;
    transactionAmount?: number;
    cardholderName?: string;
    deviceManufacturerIdentifier?: string;
    paymentDataType?: string;
    merchantTokenIdentifier?: string;
    authenticationResponses?: BasisTheory.AuthenticationResponse[];
    status?: string;
}
