/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../index";

export interface TokenServiceProviderDetails {
    tsp?: string;
    authMethod?: string;
    messageId?: string;
    eciIndicator?: string;
    assuranceDetails?: BasisTheory.AssuranceDetails;
}
