// This file was auto-generated by Fern from our API Definition.

export const VerificationResponsePasskeyContextPlatformType = {
    Web: "WEB",
    Mobile: "MOBILE",
    Native: "NATIVE",
} as const;
export type VerificationResponsePasskeyContextPlatformType =
    (typeof VerificationResponsePasskeyContextPlatformType)[keyof typeof VerificationResponsePasskeyContextPlatformType];
