// This file was auto-generated by Fern from our API Definition.

/** Card network brand (present in Mastercard responses) */
export const VerificationResponseBrand = {
    Visa: "visa",
    Mastercard: "mastercard",
} as const;
export type VerificationResponseBrand = (typeof VerificationResponseBrand)[keyof typeof VerificationResponseBrand];
