// This file was auto-generated by Fern from our API Definition.

export const VerifyAllowanceRequestCompleteProvider = {
    Agentpay: "agentpay",
    Link: "link",
} as const;
export type VerifyAllowanceRequestCompleteProvider =
    (typeof VerifyAllowanceRequestCompleteProvider)[keyof typeof VerifyAllowanceRequestCompleteProvider];
