// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../../index.js";
import { RailsRetryRequestProvider } from "../../types/RailsRetryRequestProvider.js";
import { RailsRetryRequestRail } from "../../types/RailsRetryRequestRail.js";

export const RailsRetryRequest: core.serialization.Schema<
    serializers.agentic.paymentMethods.RailsRetryRequest.Raw,
    BasisTheory.agentic.paymentMethods.RailsRetryRequest
> = core.serialization.object({
    rail: RailsRetryRequestRail,
    provider: RailsRetryRequestProvider,
});

export declare namespace RailsRetryRequest {
    export interface Raw {
        rail: RailsRetryRequestRail.Raw;
        provider: RailsRetryRequestProvider.Raw;
    }
}
