// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { TenantConnectionOptions } from "../../../../../../types/TenantConnectionOptions.js";

export const CreateTenantConnectionRequest: core.serialization.Schema<
    serializers.tenants.CreateTenantConnectionRequest.Raw,
    BasisTheory.tenants.CreateTenantConnectionRequest
> = core.serialization.object({
    strategy: core.serialization.string(),
    options: TenantConnectionOptions,
});

export declare namespace CreateTenantConnectionRequest {
    export interface Raw {
        strategy: string;
        options: TenantConnectionOptions.Raw;
    }
}
