// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         confirmationData: [{
 *                 transactionStatus: "approved",
 *                 transactionType: "purchase"
 *             }]
 *     }
 */
export interface PublishConfirmationRequest {
    confirmationData: BasisTheory.ConfirmationEntry[];
}
