/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as BasisTheory from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { ApplePayMethodToken } from "../../../../../../types/ApplePayMethodToken";

export const ApplePayTokenizeRequest: core.serialization.Schema<
    serializers.connections.ApplePayTokenizeRequest.Raw,
    BasisTheory.connections.ApplePayTokenizeRequest
> = core.serialization.object({
    applePaymentMethodToken: core.serialization.property("apple_payment_method_token", ApplePayMethodToken.optional()),
});

export declare namespace ApplePayTokenizeRequest {
    interface Raw {
        apple_payment_method_token?: ApplePayMethodToken.Raw | null;
    }
}
