// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Token } from "./Token.js";

export const AccountUpdaterRealTimeResponse: core.serialization.ObjectSchema<
    serializers.AccountUpdaterRealTimeResponse.Raw,
    BasisTheory.AccountUpdaterRealTimeResponse
> = core.serialization.object({
    newToken: core.serialization.property("new_token", Token.optional()),
    resultCode: core.serialization.property("result_code", core.serialization.string().optional()),
});

export declare namespace AccountUpdaterRealTimeResponse {
    export interface Raw {
        new_token?: Token.Raw | null;
        result_code?: string | null;
    }
}
