/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const AccountUpdaterJobListPagination: core.serialization.ObjectSchema<
    serializers.AccountUpdaterJobListPagination.Raw,
    BasisTheory.AccountUpdaterJobListPagination
> = core.serialization.object({
    pageSize: core.serialization.property("page_size", core.serialization.number().optional()),
    next: core.serialization.string().optional(),
});

export declare namespace AccountUpdaterJobListPagination {
    export interface Raw {
        page_size?: number | null;
        next?: string | null;
    }
}
