// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AllowanceRail } from "./AllowanceRail.js";
import { AllowanceStatus } from "./AllowanceStatus.js";
import { SharedPaymentAmount } from "./SharedPaymentAmount.js";
import { SharedPaymentMerchant } from "./SharedPaymentMerchant.js";

export const Allowance: core.serialization.ObjectSchema<serializers.Allowance.Raw, BasisTheory.Allowance> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        paymentMethodId: core.serialization.property("payment_method_id", core.serialization.string().optional()),
        agentId: core.serialization.property("agent_id", core.serialization.string().optional()),
        status: AllowanceStatus.optional(),
        amount: SharedPaymentAmount.optional(),
        description: core.serialization.string().optional(),
        merchant: SharedPaymentMerchant.optional(),
        amountSpent: core.serialization.property("amount_spent", SharedPaymentAmount.optional()),
        amountReserved: core.serialization.property("amount_reserved", SharedPaymentAmount.optional()),
        amountAvailable: core.serialization.property("amount_available", SharedPaymentAmount.optional()),
        credentialsCount: core.serialization.property("credentials_count", core.serialization.number().optional()),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        rails: core.serialization.list(AllowanceRail).optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    });

export declare namespace Allowance {
    export interface Raw {
        id?: string | null;
        payment_method_id?: string | null;
        agent_id?: string | null;
        status?: AllowanceStatus.Raw | null;
        amount?: SharedPaymentAmount.Raw | null;
        description?: string | null;
        merchant?: SharedPaymentMerchant.Raw | null;
        amount_spent?: SharedPaymentAmount.Raw | null;
        amount_reserved?: SharedPaymentAmount.Raw | null;
        amount_available?: SharedPaymentAmount.Raw | null;
        credentials_count?: number | null;
        metadata?: Record<string, unknown> | null;
        rails?: AllowanceRail.Raw[] | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
