// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AllowanceVerificationMethodType } from "./AllowanceVerificationMethodType.js";

export const AllowanceVerificationMethod: core.serialization.ObjectSchema<
    serializers.AllowanceVerificationMethod.Raw,
    BasisTheory.AllowanceVerificationMethod
> = core.serialization.object({
    id: core.serialization.string(),
    type: AllowanceVerificationMethodType,
    value: core.serialization.string(),
});

export declare namespace AllowanceVerificationMethod {
    export interface Raw {
        id: string;
        type: AllowanceVerificationMethodType.Raw;
        value: string;
    }
}
