// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Application } from "./Application.js";
import { Pagination } from "./Pagination.js";

export const ApplicationPaginatedList: core.serialization.ObjectSchema<
    serializers.ApplicationPaginatedList.Raw,
    BasisTheory.ApplicationPaginatedList
> = core.serialization.object({
    pagination: Pagination.optional(),
    data: core.serialization.list(Application).optional(),
});

export declare namespace ApplicationPaginatedList {
    export interface Raw {
        pagination?: Pagination.Raw | null;
        data?: Application.Raw[] | null;
    }
}
