// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AsyncReactorPendingResult: core.serialization.ObjectSchema<
    serializers.AsyncReactorPendingResult.Raw,
    BasisTheory.AsyncReactorPendingResult
> = core.serialization.object({
    status: core.serialization.string().optional(),
});

export declare namespace AsyncReactorPendingResult {
    export interface Raw {
        status?: string | null;
    }
}
