/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const AsyncReactResponse: core.serialization.ObjectSchema<
    serializers.AsyncReactResponse.Raw,
    BasisTheory.AsyncReactResponse
> = core.serialization.object({
    asyncReactorRequestId: core.serialization.string().optional(),
});

export declare namespace AsyncReactResponse {
    export interface Raw {
        asyncReactorRequestId?: string | null;
    }
}
