/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";

export const AuthenticationResponse: core.serialization.ObjectSchema<
    serializers.AuthenticationResponse.Raw,
    BasisTheory.AuthenticationResponse
> = core.serialization.object({
    merchantIdentifier: core.serialization.property("merchant_identifier", core.serialization.string().optional()),
    authenticationData: core.serialization.property("authentication_data", core.serialization.string().optional()),
    transactionAmount: core.serialization.property("transaction_amount", core.serialization.string().optional()),
});

export declare namespace AuthenticationResponse {
    export interface Raw {
        merchant_identifier?: string | null;
        authentication_data?: string | null;
        transaction_amount?: string | null;
    }
}
