/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";

export const BinDetailsBank: core.serialization.ObjectSchema<
    serializers.BinDetailsBank.Raw,
    BasisTheory.BinDetailsBank
> = core.serialization.object({
    name: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    url: core.serialization.string().optional(),
    cleanName: core.serialization.property("clean_name", core.serialization.string().optional()),
});

export declare namespace BinDetailsBank {
    export interface Raw {
        name?: string | null;
        phone?: string | null;
        url?: string | null;
        clean_name?: string | null;
    }
}
