// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AdditionalCardDetail } from "./AdditionalCardDetail.js";
import { CardIssuerDetails } from "./CardIssuerDetails.js";

export const CardDetailsResponse: core.serialization.ObjectSchema<
    serializers.CardDetailsResponse.Raw,
    BasisTheory.CardDetailsResponse
> = core.serialization.object({
    brand: core.serialization.string().optional(),
    funding: core.serialization.string().optional(),
    segment: core.serialization.string().optional(),
    issuer: CardIssuerDetails.optional(),
    additional: core.serialization.list(AdditionalCardDetail).optional(),
});

export declare namespace CardDetailsResponse {
    export interface Raw {
        brand?: string | null;
        funding?: string | null;
        segment?: string | null;
        issuer?: CardIssuerDetails.Raw | null;
        additional?: AdditionalCardDetail.Raw[] | null;
    }
}
