/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import { Address } from "./Address.js";

export const CardholderInfo: core.serialization.ObjectSchema<
    serializers.CardholderInfo.Raw,
    BasisTheory.CardholderInfo
> = core.serialization.object({
    name: core.serialization.string().optional(),
    address: Address.optional(),
});

export declare namespace CardholderInfo {
    export interface Raw {
        name?: string | null;
        address?: Address.Raw | null;
    }
}
