// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientEncryptionKeyResponse: core.serialization.ObjectSchema<
    serializers.ClientEncryptionKeyResponse.Raw,
    BasisTheory.ClientEncryptionKeyResponse
> = core.serialization.object({
    keyId: core.serialization.property("key_id", core.serialization.string().optional()),
    publicKeyPem: core.serialization.property("public_key_pem", core.serialization.string().optional()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
});

export declare namespace ClientEncryptionKeyResponse {
    export interface Raw {
        key_id?: string | null;
        public_key_pem?: string | null;
        expires_at?: string | null;
    }
}
