// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConnectionStatusDetailsAction: core.serialization.Schema<
    serializers.ConnectionStatusDetailsAction.Raw,
    BasisTheory.ConnectionStatusDetailsAction
> = core.serialization.enum_(["authorize", "reauthorize", "none"]);

export declare namespace ConnectionStatusDetailsAction {
    export type Raw = "authorize" | "reauthorize" | "none";
}
