// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConnectionPrincipalType: core.serialization.Schema<
    serializers.ConnectionPrincipalType.Raw,
    BasisTheory.ConnectionPrincipalType
> = core.serialization.enum_(["consumer", "tenant"]);

export declare namespace ConnectionPrincipalType {
    export type Raw = "consumer" | "tenant";
}
