/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const CreateDocumentRequest: core.serialization.ObjectSchema<
    serializers.CreateDocumentRequest.Raw,
    BasisTheory.CreateDocumentRequest
> = core.serialization.object({
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
});

export declare namespace CreateDocumentRequest {
    export interface Raw {
        metadata?: Record<string, string | null | undefined> | null;
    }
}
