// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CursorPagination: core.serialization.ObjectSchema<
    serializers.CursorPagination.Raw,
    BasisTheory.CursorPagination
> = core.serialization.object({
    pageSize: core.serialization.property("page_size", core.serialization.number().optional()),
    next: core.serialization.string().optional(),
});

export declare namespace CursorPagination {
    export interface Raw {
        page_size?: number | null;
        next?: string | null;
    }
}
