// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DeviceContextPlatformType } from "./DeviceContextPlatformType.js";
import { DeviceContextSessionContext } from "./DeviceContextSessionContext.js";

export const DeviceContext: core.serialization.ObjectSchema<serializers.DeviceContext.Raw, BasisTheory.DeviceContext> =
    core.serialization.object({
        screenHeight: core.serialization.property("screen_height", core.serialization.number()),
        screenWidth: core.serialization.property("screen_width", core.serialization.number()),
        userAgentString: core.serialization.property("user_agent_string", core.serialization.string()),
        languageCode: core.serialization.property("language_code", core.serialization.string()),
        timeZone: core.serialization.property("time_zone", core.serialization.string()),
        javaScriptEnabled: core.serialization.property("java_script_enabled", core.serialization.boolean()),
        clientDeviceId: core.serialization.property("client_device_id", core.serialization.string()),
        clientReferenceId: core.serialization.property("client_reference_id", core.serialization.string()),
        platformType: core.serialization.property("platform_type", DeviceContextPlatformType),
        colorDepth: core.serialization.property("color_depth", core.serialization.number().optional()),
        acceptHeader: core.serialization.property("accept_header", core.serialization.string().optional()),
        ipAddress: core.serialization.property("ip_address", core.serialization.string().optional()),
        sessionContext: core.serialization.property("session_context", DeviceContextSessionContext.optional()),
    });

export declare namespace DeviceContext {
    export interface Raw {
        screen_height: number;
        screen_width: number;
        user_agent_string: string;
        language_code: string;
        time_zone: string;
        java_script_enabled: boolean;
        client_device_id: string;
        client_reference_id: string;
        platform_type: DeviceContextPlatformType.Raw;
        color_depth?: number | null;
        accept_header?: string | null;
        ip_address?: string | null;
        session_context?: DeviceContextSessionContext.Raw | null;
    }
}
