/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const DomainRegistrationResponse: core.serialization.ObjectSchema<
    serializers.DomainRegistrationResponse.Raw,
    BasisTheory.DomainRegistrationResponse
> = core.serialization.object({
    domain: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace DomainRegistrationResponse {
    export interface Raw {
        domain?: string | null;
        status?: string | null;
    }
}
