// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetApplications: core.serialization.ObjectSchema<
    serializers.GetApplications.Raw,
    BasisTheory.GetApplications
> = core.serialization.object({
    id: core.serialization.list(core.serialization.string()).optional(),
    type: core.serialization.list(core.serialization.string()).optional(),
    page: core.serialization.number().optional(),
    start: core.serialization.string().optional(),
    size: core.serialization.number().optional(),
});

export declare namespace GetApplications {
    export interface Raw {
        id?: string[] | null;
        type?: string[] | null;
        page?: number | null;
        start?: string | null;
        size?: number | null;
    }
}
