/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";
import { CreateTokenIntentResponse } from "./CreateTokenIntentResponse";

export const GooglePayTokenizeResponse: core.serialization.ObjectSchema<
    serializers.GooglePayTokenizeResponse.Raw,
    BasisTheory.GooglePayTokenizeResponse
> = core.serialization.object({
    tokenIntent: core.serialization.property("token_intent", CreateTokenIntentResponse.optional()),
});

export declare namespace GooglePayTokenizeResponse {
    export interface Raw {
        token_intent?: CreateTokenIntentResponse.Raw | null;
    }
}
