// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ProblemDetails: core.serialization.ObjectSchema<
    serializers.ProblemDetails.Raw,
    BasisTheory.ProblemDetails
> = core.serialization
    .object({
        type: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        status: core.serialization.number().optional(),
        detail: core.serialization.string().optional(),
        instance: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace ProblemDetails {
    export interface Raw {
        type?: string | null;
        title?: string | null;
        status?: number | null;
        detail?: string | null;
        instance?: string | null;
        [key: string]: any;
    }
}
