// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SharedPaymentRailBaseAgenticToken } from "./SharedPaymentRailBaseAgenticToken.js";
import { SharedPaymentRailBaseSpt } from "./SharedPaymentRailBaseSpt.js";
import { SharedPaymentRailBaseVirtualCard } from "./SharedPaymentRailBaseVirtualCard.js";

export const SharedPaymentRailBase: core.serialization.Schema<
    serializers.SharedPaymentRailBase.Raw,
    BasisTheory.SharedPaymentRailBase
> = core.serialization
    .union("rail", {
        "agentic-token": SharedPaymentRailBaseAgenticToken,
        spt: SharedPaymentRailBaseSpt,
        "virtual-card": SharedPaymentRailBaseVirtualCard,
    })
    .transform<BasisTheory.SharedPaymentRailBase>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace SharedPaymentRailBase {
    export type Raw =
        | SharedPaymentRailBase.AgenticToken
        | SharedPaymentRailBase.Spt
        | SharedPaymentRailBase.VirtualCard;

    export interface AgenticToken extends SharedPaymentRailBaseAgenticToken.Raw {
        rail: "agentic-token";
    }

    export interface Spt extends SharedPaymentRailBaseSpt.Raw {
        rail: "spt";
    }

    export interface VirtualCard extends SharedPaymentRailBaseVirtualCard.Raw {
        rail: "virtual-card";
    }
}
