/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const StringStringKeyValuePair: core.serialization.ObjectSchema<
    serializers.StringStringKeyValuePair.Raw,
    BasisTheory.StringStringKeyValuePair
> = core.serialization.object({
    key: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace StringStringKeyValuePair {
    export interface Raw {
        key: string;
        value: string;
    }
}
