/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";

export const ThreeDsRequestorInfo: core.serialization.ObjectSchema<
    serializers.ThreeDsRequestorInfo.Raw,
    BasisTheory.ThreeDsRequestorInfo
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    url: core.serialization.string().optional(),
    discoverClientId: core.serialization.property("discover_client_id", core.serialization.string().optional()),
    discoverRequestorId: core.serialization.property("discover_requestor_id", core.serialization.string().optional()),
    amexRequestorType: core.serialization.property("amex_requestor_type", core.serialization.string().optional()),
    cbSiretNumber: core.serialization.property("cb_siret_number", core.serialization.string().optional()),
});

export declare namespace ThreeDsRequestorInfo {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        url?: string | null;
        discover_client_id?: string | null;
        discover_requestor_id?: string | null;
        amex_requestor_type?: string | null;
        cb_siret_number?: string | null;
    }
}
