/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const ThreeDsPriorAuthenticationInfo: core.serialization.ObjectSchema<
    serializers.ThreeDsPriorAuthenticationInfo.Raw,
    BasisTheory.ThreeDsPriorAuthenticationInfo
> = core.serialization.object({
    method: core.serialization.string().optional(),
    timestamp: core.serialization.string().optional(),
    referenceId: core.serialization.property("reference_id", core.serialization.string().optional()),
    data: core.serialization.string().optional(),
});

export declare namespace ThreeDsPriorAuthenticationInfo {
    export interface Raw {
        method?: string | null;
        timestamp?: string | null;
        reference_id?: string | null;
        data?: string | null;
    }
}
