/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";

export const ThreeDsMethod: core.serialization.ObjectSchema<serializers.ThreeDsMethod.Raw, BasisTheory.ThreeDsMethod> =
    core.serialization.object({
        methodUrl: core.serialization.property("method_url", core.serialization.string().optional()),
        methodCompletionIndicator: core.serialization.property(
            "method_completion_indicator",
            core.serialization.string().optional()
        ),
    });

export declare namespace ThreeDsMethod {
    interface Raw {
        method_url?: string | null;
        method_completion_indicator?: string | null;
    }
}
