/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BasisTheory from "../../api/index";
import * as core from "../../core";

export const TokenAuthentication: core.serialization.ObjectSchema<
    serializers.TokenAuthentication.Raw,
    BasisTheory.TokenAuthentication
> = core.serialization.object({
    threedsCryptogram: core.serialization.property("threeds_cryptogram", core.serialization.string().optional()),
    eciIndicator: core.serialization.property("eci_indicator", core.serialization.string().optional()),
});

export declare namespace TokenAuthentication {
    interface Raw {
        threeds_cryptogram?: string | null;
        eci_indicator?: string | null;
    }
}
