/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";

export const UpdatePrivacy: core.serialization.ObjectSchema<serializers.UpdatePrivacy.Raw, BasisTheory.UpdatePrivacy> =
    core.serialization.object({
        impactLevel: core.serialization.property("impact_level", core.serialization.string().optional()),
        restrictionPolicy: core.serialization.property("restriction_policy", core.serialization.string().optional()),
    });

export declare namespace UpdatePrivacy {
    export interface Raw {
        impact_level?: string | null;
        restriction_policy?: string | null;
    }
}
