// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ValidationProblemDetails: core.serialization.ObjectSchema<
    serializers.ValidationProblemDetails.Raw,
    BasisTheory.ValidationProblemDetails
> = core.serialization
    .object({
        errors: core.serialization
            .record(core.serialization.string(), core.serialization.list(core.serialization.string()).optional())
            .optional(),
        type: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        status: core.serialization.number().optional(),
        detail: core.serialization.string().optional(),
        instance: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace ValidationProblemDetails {
    export interface Raw {
        errors?: Record<string, string[] | null | undefined> | null;
        type?: string | null;
        title?: string | null;
        status?: number | null;
        detail?: string | null;
        instance?: string | null;
        [key: string]: any;
    }
}
