// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyAllowanceRequestStartRail: core.serialization.Schema<
    serializers.VerifyAllowanceRequestStartRail.Raw,
    BasisTheory.VerifyAllowanceRequestStartRail
> = core.serialization.enum_(["agentic-token", "spt", "virtual-card"]);

export declare namespace VerifyAllowanceRequestStartRail {
    export type Raw = "agentic-token" | "spt" | "virtual-card";
}
