// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { VerificationResponseRedirectUriType } from "./VerificationResponseRedirectUriType.js";

export const VerificationResponseRedirect: core.serialization.ObjectSchema<
    serializers.VerificationResponseRedirect.Raw,
    BasisTheory.VerificationResponseRedirect
> = core.serialization.object({
    uri: core.serialization.string().optional(),
    uriType: core.serialization.property("uri_type", VerificationResponseRedirectUriType.optional()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
});

export declare namespace VerificationResponseRedirect {
    export interface Raw {
        uri?: string | null;
        uri_type?: VerificationResponseRedirectUriType.Raw | null;
        expires_at?: string | null;
    }
}
