/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateThreeDsSessionRequest {
    pan?: string;
    token_id?: string;
    token_intent_id?: string;
    type?: string;
    device?: string;
    web_challenge_mode?: string;
    device_info?: BasisTheory.ThreeDsDeviceInfo;
    authentication_request?: BasisTheory.AuthenticateThreeDsSessionRequest;
    callback_urls?: BasisTheory.ThreeDsCallbackUrls;
}
