// This file was auto-generated by Fern from our API Definition.

export const RailsRetryRequestRail = {
    AgenticToken: "agentic-token",
    Spt: "spt",
    VirtualCard: "virtual-card",
} as const;
export type RailsRetryRequestRail = (typeof RailsRetryRequestRail)[keyof typeof RailsRetryRequestRail];
