// This file was auto-generated by Fern from our API Definition.

import * as BasisTheory from "../../src/api/index";
import { BasisTheoryClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Enrichments", () => {
    test("bankAccountVerify (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });
        const rawRequestBody = { token_id: "token_id" };
        const rawResponseBody = { status: "status" };
        server
            .mockEndpoint()
            .post("/enrichments/bank-account-verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.enrichments.bankAccountVerify({
            tokenId: "token_id",
        });
        expect(response).toEqual({
            status: "status",
        });
    });

    test("bankAccountVerify (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });
        const rawRequestBody = { token_id: "x" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/enrichments/bank-account-verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.enrichments.bankAccountVerify({
                tokenId: "x",
            });
        }).rejects.toThrow(BasisTheory.BadRequestError);
    });

    test("bankAccountVerify (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });
        const rawRequestBody = { token_id: "x" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/enrichments/bank-account-verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.enrichments.bankAccountVerify({
                tokenId: "x",
            });
        }).rejects.toThrow(BasisTheory.UnauthorizedError);
    });

    test("bankAccountVerify (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });
        const rawRequestBody = { token_id: "x" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/enrichments/bank-account-verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.enrichments.bankAccountVerify({
                tokenId: "x",
            });
        }).rejects.toThrow(BasisTheory.ForbiddenError);
    });

    test("getcarddetails (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            brand: "brand",
            funding: "funding",
            segment: "segment",
            issuer: { country: "country", name: "name" },
            additional: [{ brand: "brand", funding: "funding", segment: "segment" }],
        };
        server
            .mockEndpoint()
            .get("/enrichments/card-details")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.enrichments.getcarddetails({
            bin: "bin",
        });
        expect(response).toEqual({
            brand: "brand",
            funding: "funding",
            segment: "segment",
            issuer: {
                country: "country",
                name: "name",
            },
            additional: [
                {
                    brand: "brand",
                    funding: "funding",
                    segment: "segment",
                },
            ],
        });
    });

    test("getcarddetails (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/enrichments/card-details")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.enrichments.getcarddetails({
                bin: "bin",
            });
        }).rejects.toThrow(BasisTheory.UnauthorizedError);
    });

    test("getcarddetails (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BasisTheoryClient({ apiKey: "test", correlationId: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/enrichments/card-details")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.enrichments.getcarddetails({
                bin: "bin",
            });
        }).rejects.toThrow(BasisTheory.ForbiddenError);
    });
});
