// This file was auto-generated by Fern from our API Definition.

export const BasisTheoryEnvironment = {
    Production: "https://api.basistheory.com",
} as const;

export type BasisTheoryEnvironment = typeof BasisTheoryEnvironment.Production;
