/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as BasisTheory from "../../../../../api/index";
import * as core from "../../../../../core";

export const ClientEncryptionKeyRequest: core.serialization.Schema<
    serializers.ClientEncryptionKeyRequest.Raw,
    BasisTheory.ClientEncryptionKeyRequest
> = core.serialization.object({
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
});

export declare namespace ClientEncryptionKeyRequest {
    export interface Raw {
        expires_at?: string | null;
    }
}
