/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as BasisTheory from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface DocumentsUploadRequest {
    document?: File | fs.ReadStream | Blob | undefined;
    request?: BasisTheory.CreateDocumentRequest;
}
