/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateTokenRequest {
    id?: string;
    type?: string;
    data?: unknown;
    encrypted?: string;
    privacy?: BasisTheory.Privacy;
    metadata?: Record<string, string | undefined>;
    search_indexes?: string[];
    fingerprint_expression?: string;
    mask?: unknown;
    deduplicate_token?: boolean;
    expires_at?: string;
    containers?: string[];
    token_intent_id?: string;
}
