/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BasisTheory from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateTokenRequest {
    data?: unknown;
    privacy?: BasisTheory.UpdatePrivacy;
    metadata?: Record<string, string | undefined>;
    search_indexes?: string[];
    fingerprint_expression?: string;
    mask?: unknown;
    expires_at?: string;
    deduplicate_token?: boolean;
    containers?: string[];
}
