// This file was auto-generated by Fern from our API Definition.

import type * as BasisTheory from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const AllowancesListRequestStatus: core.serialization.Schema<
    serializers.agentic.AllowancesListRequestStatus.Raw,
    BasisTheory.agentic.AllowancesListRequestStatus
> = core.serialization.enum_(["active", "cancelled", "expired", "all"]);

export declare namespace AllowancesListRequestStatus {
    export type Raw = "active" | "cancelled" | "expired" | "all";
}
